Import('env', 'common', 'cereal', 'messaging', 'libkf', 'transformations')

loc_libs = [cereal, messaging, 'zmq', common, 'capnp', 'kj', 'pthread']

env.Program("ubloxd", ["ubloxd.cc", "ublox_msg.cc", "ubloxd_main.cc"], LIBS=loc_libs)

if GetOption("test"):
  env.Program("ubloxd_test", ["ubloxd_test.cc", "ublox_msg.cc", "ubloxd_main.cc"], LIBS=loc_libs)

lenv = env.Clone()
ekf_sym_cc = env.Object("#rednose/helpers/ekf_sym.cc")
lenv["LIBPATH"] += [libkf[0].get_dir().get_abspath()]
lenv["RPATH"] += [libkf[0].get_dir().get_abspath()]
locationd = lenv.Program("locationd", ["locationd.cc", "models/live_kf.cc", ekf_sym_cc], LIBS=loc_libs + [transformations, 'kf'])
lenv.Depends(locationd, libkf)
